language: csharp
mono: none
dotnet: 2.1.300

install:
  - dotnet restore
script:
  - dotnet build -c Release
  - dotnet test -c Release test/Option.Tests/Option.Tests.csproj
  - dotnet test -c Release test/Option.Validator.Tests/Option.Validator.Tests.csproj